version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=8000
    volumes:
      - ./backend:/app
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    platform: linux/amd64

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - PORT=3000
    command: >
      bash -c "npm install && npm run dev"
    restart: always
    platform: linux/amd64
    depends_on:
      - backend

  n8n-service:
    image: n8nio/n8n:1.32.2
    container_name: n8n-service
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securePass123
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_ENABLE_NODE_AUTOINSTALL=true
      - N8N_NODES_INCLUDE=*
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=true
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always
    platform: linux/amd64

volumes:
  n8n_data:
